apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  type: NodePort
  selector:
    app: express
  ports:
    - protocol: TCP
      port: 3000        # Service port
      targetPort: 3000 # Container port
      nodePort: 30080
